version: '3.4'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - 80:80
      - 443:443
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
  phpmyadmin:
    build:
      context: .
      dockerfile: Dockerfile.phpmyadmin
    ports:
      - 8001:80